name: Deploy to GitHub Pages

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  lint-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate HTML
        uses: svenstaro/html5validator-action@v0.7.0
        with:
          root: "."

      # ✅ CSS Validation using W3C CSS Validator
      - name: Validate CSS
        run: |
          curl -sL https://jigsaw.w3.org/css-validator/validator \
          -F file=@./styles.css -F warning=0

      # ✅ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
